"""Initial migration.

Revision ID: 8eb21106fdf1
Revises: 
Create Date: 2024-07-11 13:20:20.654135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '8eb21106fdf1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               nullable=True)
        batch_op.alter_column('cantidad',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pedido_por_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('confirmado_por_id', sa.Integer(), nullable=True))
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.alter_column('dept_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cantidad_pedida',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cantidad_entregada',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('tr_tipo',
               existing_type=sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               type_=sa.Enum('Pedido', 'Entrega', 'Recibo', 'Confirmacion'),
               nullable=True)
        batch_op.alter_column('confirmado',
               existing_type=mssql.BIT(),
               nullable=True)
        batch_op.alter_column('fecha',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_foreign_key(None, 'user', ['pedido_por_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['item_id'])
        batch_op.create_foreign_key(None, 'user', ['confirmado_por_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'departamentos', ['dept_id'], ['dept_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('rol',
               existing_type=sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               type_=sa.Enum(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'departamentos', ['dept_id'], ['dept_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('rol',
               existing_type=sa.Enum(),
               type_=sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('fecha',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('confirmado',
               existing_type=mssql.BIT(),
               nullable=False)
        batch_op.alter_column('tr_tipo',
               existing_type=sa.Enum('Pedido', 'Entrega', 'Recibo', 'Confirmacion'),
               type_=sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               nullable=False)
        batch_op.alter_column('cantidad_entregada',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cantidad_pedida',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('dept_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_column('confirmado_por_id')
        batch_op.drop_column('pedido_por_id')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               nullable=False)

    # ### end Alembic commands ###
