"""added fecha_pedido and fecha_confirmado

Revision ID: b03646fa435c
Revises: d4574e6ca214
Create Date: 2024-07-12 15:30:41.658244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03646fa435c'
down_revision = 'd4574e6ca214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_pedido', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_confirmado', sa.DateTime(), nullable=True))
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.DATETIME(), autoincrement=False, nullable=True))
        batch_op.drop_column('fecha_confirmado')
        batch_op.drop_column('fecha_pedido')

    # ### end Alembic commands ###
