"""updated relationship backrefs

Revision ID: b90f9cb66a60
Revises: b03646fa435c
Create Date: 2024-07-17 13:20:50.216944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b90f9cb66a60'
down_revision = 'b03646fa435c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=sa.VARCHAR(collation='Modern_Spanish_CI_AS'),
               type_=sa.Enum('admin', 'principal', 'usuario'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=sa.Enum('admin', 'principal', 'usuario'),
               type_=sa.VARCHAR(collation='Modern_Spanish_CI_AS'),
               existing_nullable=True)

    # ### end Alembic commands ###
