"""pedido_por_id is now nullable

Revision ID: d4574e6ca214
Revises: 8eb21106fdf1
Create Date: 2024-07-12 12:16:22.239085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4574e6ca214'
down_revision = '8eb21106fdf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.alter_column('pedido_por_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.alter_column('pedido_por_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
